# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Template_MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainGui.sizePolicy().hasHeightForWidth())
        MainGui.setSizePolicy(sizePolicy)
        MainGui.setMinimumSize(QtCore.QSize(800, 600))
        MainGui.setMaximumSize(QtCore.QSize(800, 600))
        self.tabWidget = QtWidgets.QTabWidget(MainGui)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.tabWidget.setMinimumSize(QtCore.QSize(801, 601))
        self.tabWidget.setMaximumSize(QtCore.QSize(801, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.button_manual_gimbal_left = QtWidgets.QPushButton(self.tab)
        self.button_manual_gimbal_left.setGeometry(QtCore.QRect(570, 420, 41, 41))
        self.button_manual_gimbal_left.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../res/button_manual_gimbal_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_left.setIcon(icon)
        self.button_manual_gimbal_left.setAutoRepeat(True)
        self.button_manual_gimbal_left.setObjectName("button_manual_gimbal_left")
        self.button_start_preview = QtWidgets.QPushButton(self.tab)
        self.button_start_preview.setGeometry(QtCore.QRect(10, 420, 100, 30))
        self.button_start_preview.setObjectName("button_start_preview")
        self.button_manual_gimbal_up = QtWidgets.QPushButton(self.tab)
        self.button_manual_gimbal_up.setGeometry(QtCore.QRect(590, 380, 41, 41))
        self.button_manual_gimbal_up.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../res/button_manual_gimbal_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_up.setIcon(icon1)
        self.button_manual_gimbal_up.setAutoRepeat(True)
        self.button_manual_gimbal_up.setObjectName("button_manual_gimbal_up")
        self.button_manual_gimbal_right = QtWidgets.QPushButton(self.tab)
        self.button_manual_gimbal_right.setGeometry(QtCore.QRect(610, 420, 41, 41))
        self.button_manual_gimbal_right.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../res/button_manual_gimbal_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_right.setIcon(icon2)
        self.button_manual_gimbal_right.setAutoRepeat(True)
        self.button_manual_gimbal_right.setObjectName("button_manual_gimbal_right")
        self.button_stop_tracking = QtWidgets.QPushButton(self.tab)
        self.button_stop_tracking.setGeometry(QtCore.QRect(120, 460, 100, 30))
        self.button_stop_tracking.setObjectName("button_stop_tracking")
        self.button_stop_record = QtWidgets.QPushButton(self.tab)
        self.button_stop_record.setGeometry(QtCore.QRect(120, 380, 100, 30))
        self.button_stop_record.setObjectName("button_stop_record")
        self.button_stop_preview = QtWidgets.QPushButton(self.tab)
        self.button_stop_preview.setGeometry(QtCore.QRect(120, 420, 100, 30))
        self.button_stop_preview.setObjectName("button_stop_preview")
        self.label_videostream = QtWidgets.QLabel(self.tab)
        self.label_videostream.setGeometry(QtCore.QRect(10, 10, 640, 360))
        self.label_videostream.setAutoFillBackground(True)
        self.label_videostream.setText("")
        self.label_videostream.setScaledContents(True)
        self.label_videostream.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_videostream.setObjectName("label_videostream")
        self.button_create_serial_connection = QtWidgets.QPushButton(self.tab)
        self.button_create_serial_connection.setGeometry(QtCore.QRect(10, 500, 131, 31))
        self.button_create_serial_connection.setObjectName("button_create_serial_connection")
        self.button_setup_rgb_camera = QtWidgets.QPushButton(self.tab)
        self.button_setup_rgb_camera.setGeometry(QtCore.QRect(290, 420, 131, 30))
        self.button_setup_rgb_camera.setObjectName("button_setup_rgb_camera")
        self.button_manual_gimbal_down = QtWidgets.QPushButton(self.tab)
        self.button_manual_gimbal_down.setGeometry(QtCore.QRect(590, 460, 41, 41))
        self.button_manual_gimbal_down.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../res/button_manual_gimbal_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_down.setIcon(icon3)
        self.button_manual_gimbal_down.setAutoRepeat(True)
        self.button_manual_gimbal_down.setObjectName("button_manual_gimbal_down")
        self.combobox_serial_connection_ports = QtWidgets.QComboBox(self.tab)
        self.combobox_serial_connection_ports.setGeometry(QtCore.QRect(260, 500, 131, 31))
        self.combobox_serial_connection_ports.setEditable(False)
        self.combobox_serial_connection_ports.setCurrentText("")
        self.combobox_serial_connection_ports.setObjectName("combobox_serial_connection_ports")
        self.combobox_rgb_camera_index = QtWidgets.QComboBox(self.tab)
        self.combobox_rgb_camera_index.setGeometry(QtCore.QRect(230, 420, 51, 31))
        self.combobox_rgb_camera_index.setObjectName("combobox_rgb_camera_index")
        self.button_refresh_combobox_serial_connection_ports = QtWidgets.QPushButton(self.tab)
        self.button_refresh_combobox_serial_connection_ports.setGeometry(QtCore.QRect(150, 500, 101, 31))
        self.button_refresh_combobox_serial_connection_ports.setObjectName("button_refresh_combobox_serial_connection_ports")
        self.button_setup_infrared_camera = QtWidgets.QPushButton(self.tab)
        self.button_setup_infrared_camera.setGeometry(QtCore.QRect(290, 460, 131, 30))
        self.button_setup_infrared_camera.setObjectName("button_setup_infrared_camera")
        self.button_start_tracking = QtWidgets.QPushButton(self.tab)
        self.button_start_tracking.setGeometry(QtCore.QRect(10, 460, 101, 30))
        self.button_start_tracking.setObjectName("button_start_tracking")
        self.button_start_record = QtWidgets.QPushButton(self.tab)
        self.button_start_record.setGeometry(QtCore.QRect(10, 380, 100, 30))
        self.button_start_record.setObjectName("button_start_record")
        self.combobox_infrared_camera_index = QtWidgets.QComboBox(self.tab)
        self.combobox_infrared_camera_index.setGeometry(QtCore.QRect(230, 460, 51, 31))
        self.combobox_infrared_camera_index.setObjectName("combobox_infrared_camera_index")
        self.button_refresh_combobox_camera_index = QtWidgets.QPushButton(self.tab)
        self.button_refresh_combobox_camera_index.setGeometry(QtCore.QRect(430, 440, 121, 31))
        self.button_refresh_combobox_camera_index.setObjectName("button_refresh_combobox_camera_index")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalslider_infrared_upper_boundary_hue = QtWidgets.QSlider(self.tab_2)
        self.horizontalslider_infrared_upper_boundary_hue.setGeometry(QtCore.QRect(180, 40, 160, 21))
        self.horizontalslider_infrared_upper_boundary_hue.setMaximum(179)
        self.horizontalslider_infrared_upper_boundary_hue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_upper_boundary_hue.setObjectName("horizontalslider_infrared_upper_boundary_hue")
        self.lcdnumber_infrared_upper_boundary_hue = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdnumber_infrared_upper_boundary_hue.setGeometry(QtCore.QRect(110, 40, 61, 21))
        self.lcdnumber_infrared_upper_boundary_hue.setObjectName("lcdnumber_infrared_upper_boundary_hue")
        self.horizontalslider_infrared_upper_boundary_saturation = QtWidgets.QSlider(self.tab_2)
        self.horizontalslider_infrared_upper_boundary_saturation.setGeometry(QtCore.QRect(180, 70, 160, 21))
        self.horizontalslider_infrared_upper_boundary_saturation.setMaximum(255)
        self.horizontalslider_infrared_upper_boundary_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_upper_boundary_saturation.setObjectName("horizontalslider_infrared_upper_boundary_saturation")
        self.lcdnumber_infrared_upper_boundary_saturation = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdnumber_infrared_upper_boundary_saturation.setGeometry(QtCore.QRect(110, 70, 61, 21))
        self.lcdnumber_infrared_upper_boundary_saturation.setObjectName("lcdnumber_infrared_upper_boundary_saturation")
        self.horizontalslider_infrared_upper_boundary_value = QtWidgets.QSlider(self.tab_2)
        self.horizontalslider_infrared_upper_boundary_value.setGeometry(QtCore.QRect(180, 100, 160, 21))
        self.horizontalslider_infrared_upper_boundary_value.setMaximum(255)
        self.horizontalslider_infrared_upper_boundary_value.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_upper_boundary_value.setObjectName("horizontalslider_infrared_upper_boundary_value")
        self.lcdnumber_infrared_upper_boundary_value = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdnumber_infrared_upper_boundary_value.setGeometry(QtCore.QRect(110, 100, 61, 21))
        self.lcdnumber_infrared_upper_boundary_value.setObjectName("lcdnumber_infrared_upper_boundary_value")
        self.lcdnumber_infrared_lower_boundary_value = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdnumber_infrared_lower_boundary_value.setGeometry(QtCore.QRect(350, 100, 61, 21))
        self.lcdnumber_infrared_lower_boundary_value.setObjectName("lcdnumber_infrared_lower_boundary_value")
        self.horizontalslider_infrared_lower_boundary_hue = QtWidgets.QSlider(self.tab_2)
        self.horizontalslider_infrared_lower_boundary_hue.setGeometry(QtCore.QRect(420, 40, 160, 21))
        self.horizontalslider_infrared_lower_boundary_hue.setMaximum(179)
        self.horizontalslider_infrared_lower_boundary_hue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_lower_boundary_hue.setObjectName("horizontalslider_infrared_lower_boundary_hue")
        self.horizontalslider_infrared_lower_boundary_saturation = QtWidgets.QSlider(self.tab_2)
        self.horizontalslider_infrared_lower_boundary_saturation.setGeometry(QtCore.QRect(420, 70, 160, 21))
        self.horizontalslider_infrared_lower_boundary_saturation.setMaximum(255)
        self.horizontalslider_infrared_lower_boundary_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_lower_boundary_saturation.setObjectName("horizontalslider_infrared_lower_boundary_saturation")
        self.lcdnumber_infrared_lower_boundary_hue = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdnumber_infrared_lower_boundary_hue.setGeometry(QtCore.QRect(350, 40, 61, 21))
        self.lcdnumber_infrared_lower_boundary_hue.setObjectName("lcdnumber_infrared_lower_boundary_hue")
        self.horizontalslider_infrared_lower_boundary_value = QtWidgets.QSlider(self.tab_2)
        self.horizontalslider_infrared_lower_boundary_value.setGeometry(QtCore.QRect(420, 100, 160, 21))
        self.horizontalslider_infrared_lower_boundary_value.setMaximum(255)
        self.horizontalslider_infrared_lower_boundary_value.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_lower_boundary_value.setObjectName("horizontalslider_infrared_lower_boundary_value")
        self.lcdnumber_infrared_lower_boundary_saturation = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdnumber_infrared_lower_boundary_saturation.setGeometry(QtCore.QRect(350, 70, 61, 21))
        self.lcdnumber_infrared_lower_boundary_saturation.setObjectName("lcdnumber_infrared_lower_boundary_saturation")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(110, 10, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainGui)
        self.tabWidget.setCurrentIndex(1)
        self.combobox_serial_connection_ports.setCurrentIndex(-1)
        self.horizontalslider_infrared_upper_boundary_hue.valueChanged['int'].connect(self.lcdnumber_infrared_upper_boundary_hue.display)
        self.horizontalslider_infrared_upper_boundary_saturation.valueChanged['int'].connect(self.lcdnumber_infrared_upper_boundary_saturation.display)
        self.horizontalslider_infrared_upper_boundary_value.valueChanged['int'].connect(self.lcdnumber_infrared_upper_boundary_value.display)
        self.horizontalslider_infrared_lower_boundary_hue.valueChanged['int'].connect(self.lcdnumber_infrared_lower_boundary_hue.display)
        self.horizontalslider_infrared_lower_boundary_saturation.valueChanged['int'].connect(self.lcdnumber_infrared_lower_boundary_saturation.display)
        self.horizontalslider_infrared_lower_boundary_value.valueChanged['int'].connect(self.lcdnumber_infrared_lower_boundary_value.display)
        QtCore.QMetaObject.connectSlotsByName(MainGui)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "Project Cortex"))
        self.button_start_preview.setText(_translate("MainGui", "Start Preview"))
        self.button_stop_tracking.setText(_translate("MainGui", "Stop Tracking"))
        self.button_stop_record.setText(_translate("MainGui", "Stop Recording"))
        self.button_stop_preview.setText(_translate("MainGui", "Stop Preview"))
        self.button_create_serial_connection.setText(_translate("MainGui", "CreateSerialConnection"))
        self.button_setup_rgb_camera.setText(_translate("MainGui", "Setup RGB Camera"))
        self.button_refresh_combobox_serial_connection_ports.setText(_translate("MainGui", "Refresh Serial Port"))
        self.button_setup_infrared_camera.setText(_translate("MainGui", "Setup Infrared Camera"))
        self.button_start_tracking.setText(_translate("MainGui", "Start Tracking"))
        self.button_start_record.setText(_translate("MainGui", "Start Record"))
        self.button_refresh_combobox_camera_index.setText(_translate("MainGui", "Refresh Camera Index"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainGui", "Tab 1"))
        self.label.setText(_translate("MainGui", "Upper Boundary"))
        self.label_2.setText(_translate("MainGui", "Lower Boundary"))
        self.label_3.setText(_translate("MainGui", "Hue"))
        self.label_4.setText(_translate("MainGui", "Saturation"))
        self.label_5.setText(_translate("MainGui", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainGui", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGui = QtWidgets.QWidget()
    ui = Ui_MainGui()
    ui.setupUi(MainGui)
    MainGui.show()
    sys.exit(app.exec_())

