# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Template_MainGui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainGui.sizePolicy().hasHeightForWidth())
        MainGui.setSizePolicy(sizePolicy)
        self.spinbox_infrared_erode_iterations = QtWidgets.QSpinBox(MainGui)
        self.spinbox_infrared_erode_iterations.setGeometry(QtCore.QRect(940, 510, 41, 21))
        self.spinbox_infrared_erode_iterations.setMinimum(0)
        self.spinbox_infrared_erode_iterations.setMaximum(10)
        self.spinbox_infrared_erode_iterations.setSingleStep(1)
        self.spinbox_infrared_erode_iterations.setProperty("value", 0)
        self.spinbox_infrared_erode_iterations.setObjectName("spinbox_infrared_erode_iterations")
        self.button_setup_infrared_camera = QtWidgets.QPushButton(MainGui)
        self.button_setup_infrared_camera.setGeometry(QtCore.QRect(320, 500, 131, 30))
        self.button_setup_infrared_camera.setObjectName("button_setup_infrared_camera")
        self.label = QtWidgets.QLabel(MainGui)
        self.label.setGeometry(QtCore.QRect(660, 230, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.spinbox_infrared_dilate_iterations = QtWidgets.QSpinBox(MainGui)
        self.spinbox_infrared_dilate_iterations.setGeometry(QtCore.QRect(940, 540, 41, 21))
        self.spinbox_infrared_dilate_iterations.setMinimum(0)
        self.spinbox_infrared_dilate_iterations.setMaximum(10)
        self.spinbox_infrared_dilate_iterations.setProperty("value", 0)
        self.spinbox_infrared_dilate_iterations.setObjectName("spinbox_infrared_dilate_iterations")
        self.horizontalslider_infrared_upper_boundary_hue = QtWidgets.QSlider(MainGui)
        self.horizontalslider_infrared_upper_boundary_hue.setGeometry(QtCore.QRect(830, 260, 151, 21))
        self.horizontalslider_infrared_upper_boundary_hue.setMaximum(179)
        self.horizontalslider_infrared_upper_boundary_hue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_upper_boundary_hue.setObjectName("horizontalslider_infrared_upper_boundary_hue")
        self.button_refresh_combobox_serial_connection_ports = QtWidgets.QPushButton(MainGui)
        self.button_refresh_combobox_serial_connection_ports.setGeometry(QtCore.QRect(600, 540, 121, 31))
        self.button_refresh_combobox_serial_connection_ports.setObjectName("button_refresh_combobox_serial_connection_ports")
        self.lcdnumber_infrared_upper_boundary_value = QtWidgets.QLCDNumber(MainGui)
        self.lcdnumber_infrared_upper_boundary_value.setGeometry(QtCore.QRect(760, 320, 61, 21))
        self.lcdnumber_infrared_upper_boundary_value.setObjectName("lcdnumber_infrared_upper_boundary_value")
        self.label_11 = QtWidgets.QLabel(MainGui)
        self.label_11.setGeometry(QtCore.QRect(660, 440, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(MainGui)
        self.label_13.setGeometry(QtCore.QRect(660, 410, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.button_manual_gimbal_left = QtWidgets.QPushButton(MainGui)
        self.button_manual_gimbal_left.setGeometry(QtCore.QRect(230, 500, 41, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/man_k/res/button_manual_gimbal_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_left.setIcon(icon)
        self.button_manual_gimbal_left.setAutoRepeat(True)
        self.button_manual_gimbal_left.setObjectName("button_manual_gimbal_left")
        self.label_5 = QtWidgets.QLabel(MainGui)
        self.label_5.setGeometry(QtCore.QRect(660, 320, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.button_stop_preview = QtWidgets.QPushButton(MainGui)
        self.button_stop_preview.setGeometry(QtCore.QRect(120, 500, 100, 30))
        self.button_stop_preview.setObjectName("button_stop_preview")
        self.label_9 = QtWidgets.QLabel(MainGui)
        self.label_9.setGeometry(QtCore.QRect(660, 380, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.spinbox_infrared_blur_kernalsize = QtWidgets.QSpinBox(MainGui)
        self.spinbox_infrared_blur_kernalsize.setGeometry(QtCore.QRect(940, 480, 41, 21))
        self.spinbox_infrared_blur_kernalsize.setMinimum(0)
        self.spinbox_infrared_blur_kernalsize.setMaximum(5)
        self.spinbox_infrared_blur_kernalsize.setSingleStep(1)
        self.spinbox_infrared_blur_kernalsize.setObjectName("spinbox_infrared_blur_kernalsize")
        self.label_12 = QtWidgets.QLabel(MainGui)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.button_stop_record = QtWidgets.QPushButton(MainGui)
        self.button_stop_record.setGeometry(QtCore.QRect(120, 460, 100, 30))
        self.button_stop_record.setObjectName("button_stop_record")
        self.horizontalslider_infrared_lower_boundary_hue = QtWidgets.QSlider(MainGui)
        self.horizontalslider_infrared_lower_boundary_hue.setGeometry(QtCore.QRect(830, 380, 151, 21))
        self.horizontalslider_infrared_lower_boundary_hue.setMaximum(179)
        self.horizontalslider_infrared_lower_boundary_hue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_lower_boundary_hue.setObjectName("horizontalslider_infrared_lower_boundary_hue")
        self.lcdnumber_infrared_upper_boundary_hue = QtWidgets.QLCDNumber(MainGui)
        self.lcdnumber_infrared_upper_boundary_hue.setGeometry(QtCore.QRect(760, 260, 61, 21))
        self.lcdnumber_infrared_upper_boundary_hue.setObjectName("lcdnumber_infrared_upper_boundary_hue")
        self.button_start_preview = QtWidgets.QPushButton(MainGui)
        self.button_start_preview.setGeometry(QtCore.QRect(10, 500, 100, 30))
        self.button_start_preview.setObjectName("button_start_preview")
        self.combobox_rgb_camera_index = QtWidgets.QComboBox(MainGui)
        self.combobox_rgb_camera_index.setGeometry(QtCore.QRect(460, 460, 51, 31))
        self.combobox_rgb_camera_index.setObjectName("combobox_rgb_camera_index")
        self.combobox_serial_connection_ports = QtWidgets.QComboBox(MainGui)
        self.combobox_serial_connection_ports.setGeometry(QtCore.QRect(460, 540, 131, 31))
        self.combobox_serial_connection_ports.setEditable(False)
        self.combobox_serial_connection_ports.setCurrentText("")
        self.combobox_serial_connection_ports.setObjectName("combobox_serial_connection_ports")
        self.label_3 = QtWidgets.QLabel(MainGui)
        self.label_3.setGeometry(QtCore.QRect(660, 260, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.button_start_tracking = QtWidgets.QPushButton(MainGui)
        self.button_start_tracking.setGeometry(QtCore.QRect(10, 540, 101, 30))
        self.button_start_tracking.setObjectName("button_start_tracking")
        self.label_2 = QtWidgets.QLabel(MainGui)
        self.label_2.setGeometry(QtCore.QRect(660, 350, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_rgb_camera_videostream = QtWidgets.QLabel(MainGui)
        self.label_rgb_camera_videostream.setGeometry(QtCore.QRect(10, 40, 640, 360))
        self.label_rgb_camera_videostream.setAutoFillBackground(False)
        self.label_rgb_camera_videostream.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_rgb_camera_videostream.setText("")
        self.label_rgb_camera_videostream.setScaledContents(True)
        self.label_rgb_camera_videostream.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_rgb_camera_videostream.setObjectName("label_rgb_camera_videostream")
        self.button_manual_gimbal_down = QtWidgets.QPushButton(MainGui)
        self.button_manual_gimbal_down.setGeometry(QtCore.QRect(250, 530, 41, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/man_k/res/button_manual_gimbal_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_down.setIcon(icon1)
        self.button_manual_gimbal_down.setAutoRepeat(True)
        self.button_manual_gimbal_down.setObjectName("button_manual_gimbal_down")
        self.lcdnumber_infrared_upper_boundary_saturation = QtWidgets.QLCDNumber(MainGui)
        self.lcdnumber_infrared_upper_boundary_saturation.setGeometry(QtCore.QRect(760, 290, 61, 21))
        self.lcdnumber_infrared_upper_boundary_saturation.setObjectName("lcdnumber_infrared_upper_boundary_saturation")
        self.button_manual_gimbal_up = QtWidgets.QPushButton(MainGui)
        self.button_manual_gimbal_up.setGeometry(QtCore.QRect(250, 470, 41, 31))
        self.button_manual_gimbal_up.setAutoRepeat(True)
        self.button_manual_gimbal_up.setObjectName("button_manual_gimbal_up")
        self.label_Infrared_camera_preview_2 = QtWidgets.QLabel(MainGui)
        self.label_Infrared_camera_preview_2.setGeometry(QtCore.QRect(660, 40, 320, 180))
        self.label_Infrared_camera_preview_2.setAutoFillBackground(False)
        self.label_Infrared_camera_preview_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.label_Infrared_camera_preview_2.setText("")
        self.label_Infrared_camera_preview_2.setScaledContents(True)
        self.label_Infrared_camera_preview_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_Infrared_camera_preview_2.setObjectName("label_Infrared_camera_preview_2")
        self.label_4 = QtWidgets.QLabel(MainGui)
        self.label_4.setGeometry(QtCore.QRect(660, 290, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_10 = QtWidgets.QLabel(MainGui)
        self.label_10.setGeometry(QtCore.QRect(660, 10, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(MainGui)
        self.label_7.setGeometry(QtCore.QRect(840, 540, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalslider_infrared_lower_boundary_saturation = QtWidgets.QSlider(MainGui)
        self.horizontalslider_infrared_lower_boundary_saturation.setGeometry(QtCore.QRect(830, 410, 151, 21))
        self.horizontalslider_infrared_lower_boundary_saturation.setMaximum(255)
        self.horizontalslider_infrared_lower_boundary_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_lower_boundary_saturation.setObjectName("horizontalslider_infrared_lower_boundary_saturation")
        self.lcdnumber_infrared_lower_boundary_hue = QtWidgets.QLCDNumber(MainGui)
        self.lcdnumber_infrared_lower_boundary_hue.setGeometry(QtCore.QRect(760, 380, 61, 21))
        self.lcdnumber_infrared_lower_boundary_hue.setObjectName("lcdnumber_infrared_lower_boundary_hue")
        self.button_stop_tracking = QtWidgets.QPushButton(MainGui)
        self.button_stop_tracking.setGeometry(QtCore.QRect(120, 540, 100, 30))
        self.button_stop_tracking.setObjectName("button_stop_tracking")
        self.label_8 = QtWidgets.QLabel(MainGui)
        self.label_8.setGeometry(QtCore.QRect(840, 480, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.combobox_infrared_camera_index = QtWidgets.QComboBox(MainGui)
        self.combobox_infrared_camera_index.setGeometry(QtCore.QRect(460, 500, 51, 31))
        self.combobox_infrared_camera_index.setObjectName("combobox_infrared_camera_index")
        self.button_manual_gimbal_right = QtWidgets.QPushButton(MainGui)
        self.button_manual_gimbal_right.setGeometry(QtCore.QRect(270, 500, 41, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/man_k/res/button_manual_gimbal_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_manual_gimbal_right.setIcon(icon2)
        self.button_manual_gimbal_right.setAutoRepeat(True)
        self.button_manual_gimbal_right.setObjectName("button_manual_gimbal_right")
        self.button_create_serial_connection = QtWidgets.QPushButton(MainGui)
        self.button_create_serial_connection.setGeometry(QtCore.QRect(320, 540, 131, 31))
        self.button_create_serial_connection.setObjectName("button_create_serial_connection")
        self.horizontalslider_infrared_upper_boundary_value = QtWidgets.QSlider(MainGui)
        self.horizontalslider_infrared_upper_boundary_value.setGeometry(QtCore.QRect(830, 320, 151, 21))
        self.horizontalslider_infrared_upper_boundary_value.setMaximum(255)
        self.horizontalslider_infrared_upper_boundary_value.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_upper_boundary_value.setObjectName("horizontalslider_infrared_upper_boundary_value")
        self.horizontalslider_infrared_lower_boundary_value = QtWidgets.QSlider(MainGui)
        self.horizontalslider_infrared_lower_boundary_value.setGeometry(QtCore.QRect(830, 440, 151, 21))
        self.horizontalslider_infrared_lower_boundary_value.setMaximum(255)
        self.horizontalslider_infrared_lower_boundary_value.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_lower_boundary_value.setObjectName("horizontalslider_infrared_lower_boundary_value")
        self.lcdnumber_infrared_lower_boundary_saturation = QtWidgets.QLCDNumber(MainGui)
        self.lcdnumber_infrared_lower_boundary_saturation.setGeometry(QtCore.QRect(760, 410, 61, 21))
        self.lcdnumber_infrared_lower_boundary_saturation.setObjectName("lcdnumber_infrared_lower_boundary_saturation")
        self.button_start_record = QtWidgets.QPushButton(MainGui)
        self.button_start_record.setGeometry(QtCore.QRect(10, 460, 100, 30))
        self.button_start_record.setObjectName("button_start_record")
        self.button_refresh_combobox_camera_index = QtWidgets.QPushButton(MainGui)
        self.button_refresh_combobox_camera_index.setGeometry(QtCore.QRect(520, 460, 121, 71))
        self.button_refresh_combobox_camera_index.setObjectName("button_refresh_combobox_camera_index")
        self.button_setup_rgb_camera = QtWidgets.QPushButton(MainGui)
        self.button_setup_rgb_camera.setGeometry(QtCore.QRect(320, 460, 131, 30))
        self.button_setup_rgb_camera.setObjectName("button_setup_rgb_camera")
        self.lcdnumber_infrared_lower_boundary_value = QtWidgets.QLCDNumber(MainGui)
        self.lcdnumber_infrared_lower_boundary_value.setGeometry(QtCore.QRect(760, 440, 61, 21))
        self.lcdnumber_infrared_lower_boundary_value.setObjectName("lcdnumber_infrared_lower_boundary_value")
        self.label_6 = QtWidgets.QLabel(MainGui)
        self.label_6.setGeometry(QtCore.QRect(840, 510, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalslider_infrared_upper_boundary_saturation = QtWidgets.QSlider(MainGui)
        self.horizontalslider_infrared_upper_boundary_saturation.setGeometry(QtCore.QRect(830, 290, 151, 21))
        self.horizontalslider_infrared_upper_boundary_saturation.setMaximum(255)
        self.horizontalslider_infrared_upper_boundary_saturation.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalslider_infrared_upper_boundary_saturation.setObjectName("horizontalslider_infrared_upper_boundary_saturation")

        self.retranslateUi(MainGui)
        self.horizontalslider_infrared_upper_boundary_hue.valueChanged['int'].connect(self.lcdnumber_infrared_upper_boundary_hue.display)
        self.horizontalslider_infrared_upper_boundary_saturation.valueChanged['int'].connect(self.lcdnumber_infrared_upper_boundary_saturation.display)
        self.horizontalslider_infrared_upper_boundary_value.valueChanged['int'].connect(self.lcdnumber_infrared_upper_boundary_value.display)
        self.horizontalslider_infrared_lower_boundary_hue.valueChanged['int'].connect(self.lcdnumber_infrared_lower_boundary_hue.display)
        self.horizontalslider_infrared_lower_boundary_saturation.valueChanged['int'].connect(self.lcdnumber_infrared_lower_boundary_saturation.display)
        self.horizontalslider_infrared_lower_boundary_value.valueChanged['int'].connect(self.lcdnumber_infrared_lower_boundary_value.display)
        QtCore.QMetaObject.connectSlotsByName(MainGui)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "Project Cortex"))
        self.button_setup_infrared_camera.setText(_translate("MainGui", "Setup Infrared Camera"))
        self.label.setText(_translate("MainGui", "Upper Boundary"))
        self.button_refresh_combobox_serial_connection_ports.setText(_translate("MainGui", "Refresh Serial Port"))
        self.label_11.setText(_translate("MainGui", "Value"))
        self.label_13.setText(_translate("MainGui", "Saturation"))
        self.button_manual_gimbal_left.setText(_translate("MainGui", "🢀"))
        self.label_5.setText(_translate("MainGui", "Value"))
        self.button_stop_preview.setText(_translate("MainGui", "Stop Preview"))
        self.label_9.setText(_translate("MainGui", "Hue"))
        self.label_12.setText(_translate("MainGui", "RGB Camera"))
        self.button_stop_record.setText(_translate("MainGui", "Stop Recording"))
        self.button_start_preview.setText(_translate("MainGui", "Start Preview"))
        self.label_3.setText(_translate("MainGui", "Hue"))
        self.button_start_tracking.setText(_translate("MainGui", "Start Tracking"))
        self.label_2.setText(_translate("MainGui", "Lower Boundary"))
        self.button_manual_gimbal_down.setText(_translate("MainGui", "🢃"))
        self.button_manual_gimbal_up.setText(_translate("MainGui", "🢁"))
        self.label_4.setText(_translate("MainGui", "Saturation"))
        self.label_10.setText(_translate("MainGui", "Infrared Camera"))
        self.label_7.setText(_translate("MainGui", "Dilate"))
        self.button_stop_tracking.setText(_translate("MainGui", "Stop Tracking"))
        self.label_8.setText(_translate("MainGui", "Blur"))
        self.button_manual_gimbal_right.setText(_translate("MainGui", "🢂"))
        self.button_create_serial_connection.setText(_translate("MainGui", "CreateSerialConnection"))
        self.button_start_record.setText(_translate("MainGui", "Start Record"))
        self.button_refresh_combobox_camera_index.setText(_translate("MainGui", "Refresh Camera Index"))
        self.button_setup_rgb_camera.setText(_translate("MainGui", "Setup RGB Camera"))
        self.label_6.setText(_translate("MainGui", "Erode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGui = QtWidgets.QWidget()
    ui = Ui_MainGui()
    ui.setupUi(MainGui)
    MainGui.show()
    sys.exit(app.exec_())

